---
title: "Reporte análisis de factores"
author: "David Flores"
date: "2026-07-02"
output: html_document
---

```{r setup, include=FALSE}
library(EFAtools)
library(tidyverse)
library(multiUS)
library(parallel)
library(future)
library(reshape2)

pgfull<-read.table("C:/Users/100032608/Downloads/pgfull.txt", header=TRUE)
pgfull
```

```{r}
pg_especies<-pgfull[,1:54]
```

```{r}
BARTLETT(pg_especies)
KMO(pg_especies)
ani<-antiImage(pg_especies)
print(ani,digits=3)
```

```{r}
PARALLEL(pg_especies,eigen_type="SMC")
N_FACTORS(pg_especies,criteria=c("PARALLEL","EKC","SMT"),
                       eigen_type_other = c("SMC","PCA"))
```

```{r}
EFA(pg_especies,n_factors= 7)
Factores<-EFA(pg_especies,n_factors=7)


F1<-Factores$unrot_loadings[,1]
F2<-Factores$unrot_loadings[,2]
F3<-Factores$unrot_loadings[,3]
F4<-Factores$unrot_loadings[,4]
F5<-Factores$unrot_loadings[,5]
F6<-Factores$unrot_loadings[,6]
F7<-Factores$unrot_loadings[,7]

Facts<-data.frame(F1,F2,F3,F4,F5,F6,F7)
view(Facts)
vars<-rownames(Facts)
Facts<-mutate(Facts,vars=vars)

```

```{r}
Facts2 <- melt(Facts, id="vars", 
               measure=c("F1","F2","F3","F4","F5","F6","F7"), 
               variable.name="Factor", value.name="Loading")

view(Facts2)

ggplot(Facts2, aes(x= vars, y = abs(Loading), fill=Loading)) + 
  facet_wrap(~ Factor, nrow=1) + 
  geom_bar(stat="identity") + 
  coord_flip() + 
  scale_fill_gradient2(name = "Loading", 
                       high = "blue", mid = "white", low = "red", 
                       midpoint=0) +
  ylab("Magnitud de la carga") + 
  theme_bw(base_size=10)+
  theme(axis.text.y=element_text(size=5))
```

```{r}
vmx1<-EFA(pg_especies, n_factors = 7, rotation = "varimax")
vmx1

final<-factanal(pg_especies,factors=7,rotation="varimax",scores="regression")
Factor1<-final$scores[,1]
Factor2<-final$scores[,2]
Factor3<-final$scores[,3]
Factor4<-final$scores[,4]
Factor5<-final$scores[,5]
Factor6<-final$scores[,6]
Factor7<-final$scores[,7]
ambientales<-pgfull[,57:59]
cor(Factor1,ambientales)
cor(Factor2,ambientales)
cor(Factor3,ambientales)
cor(Factor4,ambientales)
cor(Factor5,ambientales)
cor(Factor6,ambientales)
cor(Factor7,ambientales)
```

